version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: halu5071/edwards-doc:1.5
    environment:
      _JAVA_OPTIONS: "-Xms2048m -Xmx2048m"
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "eddsa/build.gradle" }}
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "eddsa/build.gradle" }}
      - run:
          name: Prepare googletest
          command: |
                chmod u+x setup.sh
                ./setup.sh
      - store_test_results:
          path: ~/code/3rdparty/googletest-release-1.8.0/googletest/build/CMakeFiles/
      - store_artifacts:
          path: ~/code/3rdparty/googletest-release-1.8.0/googletest/build/CMakeFiles/
      - run:
          name: EdDsa Unit Test
          command: ./gradlew eddsa:test
      - run:
          name: Coverage
          command: |
                ./gradlew :eddsa:check
                ./gradlew :eddsa:jacocoTestReport
      - run:
          name: Codecov
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: Benchmark
          command: |
                ./gradlew benchmark:clean
                ./gradlew benchmark:jmh
                ./gradlew benchmark:jmhReport
      - store_test_results:
          path: ~/code/benchmark/build/reports/jmh
      - store_artifacts:
          path: ~/code/benchmark/build/reports/jmh
      - run:
          name: Publish Artifact
          command: |
                if [ $CIRCLE_BRANCH = "master" ]; then
                    ./gradlew eddsa:jar
                    ./gradlew eddsa:bintrayUpload
                fi
dependencies:
  pre:
    - mkdir $ANDROID_HOME/licenses
    - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license
    - sudo pip install codecov